language: node_js
node_js:
  - '12'
sudo: required
dist: trusty
addons:
  chrome: stable
cache:
  directories:
    - $HOME/.npm
branches:
  only: ['master']
env:
  - ENV=CI
# before_install:
#   - export CHROME_BIN=chromium-browser
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
install:
  - npm ci --ignore-scripts
before_script:
  - npm run packages:lint
  - npm run packages:test
script:
  # run build script specified in package.json
  - npm run packages:build
  #
  - npm run build:prod # demo
  - npm run compodoc # docs
after_success:
  - echo 'success'
deploy:
  skip_cleanup: true
  provider: pages
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist/demo/
  on:
    branch: master
